package com.zijianxin.website.workflow;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class WorkflowDraftService {

    private static final Logger log = LoggerFactory.getLogger(WorkflowDraftService.class);
    private static final List<String> JUNK_CONTACT_TOKENS = List.of(
            "联系我们", "联系", "联系方式", "关于我们", "首页", "产品中心", "新闻资讯", "网站地图",
            "contact", "contact us", "contacts", "about", "about us", "home", "products", "news", "support",
            "menu", "navigation", "nav", "sales", "service", "info"
    );

    private final SettingsService settingsService;
    private final AiCompletionService aiCompletionService;

    public WorkflowDraftService(SettingsService settingsService, AiCompletionService aiCompletionService) {
        this.settingsService = settingsService;
        this.aiCompletionService = aiCompletionService;
    }

    public WorkflowModels.DraftResponse generateDraft(WorkflowModels.DraftRequest request) {
        SettingsModels.AppSettings settings = settingsService.getSettings();
        SettingsModels.AiSettings ai = settings.ai();
        SettingsModels.MailSettings mail = settings.mail();

        String companyName = fallback(request.companyName(), ai.defaultCompanyName());
        String productName = fallback(request.productName(), ai.defaultProductName());
        String valueProposition = fallback(request.valueProposition(), ai.defaultValueProposition());
        String language = fallback(request.language(), ai.defaultLanguage());
        String tone = fallback(request.tone(), ai.defaultTone());
        String callToAction = fallback(request.callToAction(), ai.defaultCallToAction());
        String senderName = fallback(mail.senderName(), "John");
        String senderEmail = fallback(mail.senderEmail(), "");

        List<WorkflowModels.CustomerLead> recipients = safeRecipients(request.recipients());
        WorkflowModels.CustomerLead firstRecipient = recipients.isEmpty()
                ? new WorkflowModels.CustomerLead(
                "placeholder",
                "Selected Prospect",
                "",
                "Target Market",
                "Business Contact",
                "",
                "Website",
                "Generated from current settings"
        )
                : recipients.get(0);

        String systemPrompt = buildDraftSystemPrompt(language, tone);
        String userPrompt = buildDraftUserPrompt(
                companyName,
                productName,
                valueProposition,
                callToAction,
                language,
                recipients,
                firstRecipient,
                senderName,
                senderEmail,
                request.template()
        );

        log.info("Generating draft with AI. recipients={}, provider={}, model={}, targetLanguage={}",
                recipients.size(), ai.provider(), ai.model(), language);
        String raw = aiCompletionService.complete(ai, systemPrompt, userPrompt);
        ParsedDraft parsedDraft = parseDraft(raw);

        String analysis = "Generated by real AI using the configured Base URL / API Key / Model.";
        List<String> followUpTips = buildFollowUpTips(firstRecipient, recipients.size());
        String subject = cleanGeneratedText(
                fallback(parsedDraft.subject(), buildFallbackSubject(companyName, productName, firstRecipient.companyName())),
                companyName,
                productName,
                firstRecipient,
                senderName
        );
        String body = cleanGeneratedBody(cleanGeneratedText(
                fallback(parsedDraft.body(), raw),
                companyName,
                productName,
                firstRecipient,
                senderName
        ));

        return new WorkflowModels.DraftResponse(
                subject,
                body,
                analysis,
                followUpTips
        );
    }

    public WorkflowModels.TranslateEmailResponse translateEmail(WorkflowModels.TranslateEmailRequest request) {
        SettingsModels.AiSettings ai = settingsService.getSettings().ai();

        String targetLanguage = fallback(request.targetLanguage(), ai.defaultLanguage());
        String targetLanguageName = resolveLanguageName(targetLanguage);

        String systemPrompt = buildTranslationSystemPrompt(targetLanguageName);
        String userPrompt = buildTranslationUserPrompt(
                fallback(request.subject(), ""),
                fallback(request.body(), ""),
                targetLanguageName
        );

        log.info("Translating email with AI. provider={}, model={}, targetLanguage={}",
                ai.provider(), ai.model(), targetLanguage);
        String raw = aiCompletionService.complete(ai, systemPrompt, userPrompt);
        ParsedDraft parsedDraft = parseDraft(raw);

        return new WorkflowModels.TranslateEmailResponse(
                fallback(parsedDraft.subject(), request.subject()),
                fallback(parsedDraft.body(), request.body())
        );
    }

    public WorkflowModels.DraftResponse optimizeDraft(WorkflowModels.DraftOptimizationRequest request) {
        SettingsModels.AppSettings settings = settingsService.getSettings();
        SettingsModels.AiSettings ai = settings.ai();
        SettingsModels.MailSettings mail = settings.mail();

        String language = fallback(request.language(), ai.defaultLanguage());
        String tone = fallback(request.tone(), ai.defaultTone());
        String companyName = fallback(request.companyName(), ai.defaultCompanyName());
        String productName = fallback(request.productName(), ai.defaultProductName());
        String valueProposition = fallback(request.valueProposition(), ai.defaultValueProposition());
        String callToAction = fallback(request.callToAction(), ai.defaultCallToAction());
        String optimizationLogic = fallback(ai.defaultOptimizationLogic(), "");
        String senderName = fallback(mail.senderName(), "John");
        String senderEmail = fallback(mail.senderEmail(), "");

        List<WorkflowModels.CustomerLead> recipients = safeRecipients(request.recipients());
        WorkflowModels.CustomerLead firstRecipient = recipients.isEmpty()
                ? new WorkflowModels.CustomerLead(
                "placeholder",
                "Selected Prospect",
                "",
                "Target Market",
                "Business Contact",
                "",
                "Website",
                "Generated from current settings"
        )
                : recipients.get(0);

        String systemPrompt = buildOptimizationSystemPrompt(language, tone);
        String userPrompt = buildOptimizationUserPrompt(
                request.subject(),
                request.body(),
                companyName,
                productName,
                valueProposition,
                callToAction,
                language,
                firstRecipient,
                optimizationLogic,
                senderName,
                senderEmail,
                request.template()
        );

        log.info("Optimizing draft with AI. recipient={}, provider={}, model={}, targetLanguage={}",
                firstRecipient.companyName(), ai.provider(), ai.model(), language);
        String raw = aiCompletionService.complete(ai, systemPrompt, userPrompt);
        ParsedDraft parsedDraft = parseDraft(raw);
        String subject = cleanGeneratedText(fallback(parsedDraft.subject(), request.subject()), companyName, productName, firstRecipient, senderName);
        String body = cleanGeneratedBody(cleanGeneratedText(fallback(parsedDraft.body(), request.body()), companyName, productName, firstRecipient, senderName));

        return new WorkflowModels.DraftResponse(
                subject,
                body,
                "Optimized by real AI using the configured Base URL / API Key / Model.",
                buildFollowUpTips(firstRecipient, recipients.size())
        );
    }

    private String buildDraftSystemPrompt(String language, String tone) {
        String languageName = resolveLanguageName(language);
        return """
                You are an expert B2B outbound email copywriter.
                Generate a concise, realistic, high-conversion cold outreach email.
                Output format:
                SUBJECT: <email subject>
                BODY:
                <email body>
                                
                Requirements:
                - Keep the email natural and businesslike.
                - Write the entire subject and body in %s.
                - Do not reply in any other language.
                - Do not mix multiple languages in the final email.
                - Do not add a second translated version.
                - Respect the requested tone.
                - Do not use markdown.
                - Do not fabricate impossible claims.
                - Mention recipient context when available.
                - End with a clear CTA.
                - Keep non-Chinese proper nouns (e.g., English company names, personal names, websites, email addresses) exactly as provided.
                - CRITICAL: If the target output language is NOT Chinese, ALL Chinese text used in the email (company names, product names, value propositions, descriptions, and any other Chinese phrases) must be translated into the target language. Do NOT leave any Chinese characters in the final email.
                Current language code: %s
                Current language name: %s
                Current tone: %s
                """.formatted(languageName, language, languageName, tone);
    }

    private String buildOptimizationSystemPrompt(String language, String tone) {
        String languageName = resolveLanguageName(language);
        return """
                You are an expert B2B outbound email copywriter and editor.
                Optimize the provided draft for clarity, relevance, personalization, and reply rate.
                Output format:
                SUBJECT: <optimized subject>
                BODY:
                <optimized email body>
                                
                Requirements:
                - Keep the meaning aligned with the original draft.
                - Improve readability and conversion.
                - Rewrite the entire subject and body in %s.
                - Do not reply in any other language.
                - Do not mix multiple languages in the final email.
                - Do not add a second translated version.
                - Respect the requested tone.
                - Do not use markdown.
                - Keep it concise and realistic.
                - Keep non-Chinese proper nouns (e.g., English company names, personal names, websites, email addresses) exactly as provided.
                - CRITICAL: If the target output language is NOT Chinese, ALL Chinese text used in the email (company names, product names, value propositions, descriptions, and any other Chinese phrases) must be translated into the target language. Do NOT leave any Chinese characters in the final email.
                Current language code: %s
                Current language name: %s
                Current tone: %s
                """.formatted(languageName, language, languageName, tone);
    }

    private String buildDraftUserPrompt(
            String companyName,
            String productName,
            String valueProposition,
            String callToAction,
            String language,
            List<WorkflowModels.CustomerLead> recipients,
            WorkflowModels.CustomerLead firstRecipient,
            String senderName,
            String senderEmail,
            WorkflowModels.EmailTemplateContext template
    ) {
        String languageName = resolveLanguageName(language);
        boolean nonChinese = isNonChineseTarget(language);
        String recipientContact = cleanRecipientContactName(firstRecipient.contactName());
        String recipientEmail = fallback(firstRecipient.email(), "N/A");
        boolean hasRealContact = !recipientContact.isBlank();
        String translateDirective = nonChinese
                ? "\nMANDATORY TRANSLATION DIRECTIVE: The fields marked with [TRANSLATE TO %s] below contain Chinese text. You MUST translate every Chinese character into %s when composing the email. Do NOT keep any Chinese characters in the final subject or body.\n".formatted(languageName, languageName)
                : "";
        String cnCompany = nonChinese && containsChinese(companyName) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnProduct = nonChinese && containsChinese(productName) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnValue = nonChinese && containsChinese(valueProposition) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnCta = nonChinese && containsChinese(callToAction) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnFit = nonChinese && containsChinese(firstRecipient.fitNote()) ? " [TRANSLATE TO " + languageName + "]" : "";
        String templateSection = buildTemplatePromptSection(template, languageName, nonChinese);
        return """
                Target output language: %s (%s)
                Final email rule: the subject and body must be fully written in %s only.%s
                                
                Sender company: %s%s
                Sender name: %s
                Sender email: %s
                Product / solution: %s%s
                Value proposition: %s%s
                CTA: %s%s
                Recipient count: %s
                Primary recipient company: %s
                Primary recipient country: %s
                Primary recipient contact: %s
                Has verified personal contact name: %s
                Primary recipient email: %s
                Fit note: %s%s
                %s
                                
                Please write a cold outreach email for the primary recipient while keeping it reusable for the selected batch.
                If there is no verified personal contact name, use a natural generic greeting such as "您好" or "Hello" instead of inventing a name.
                Do not use website navigation text, button text, or page labels as a person's name.
                Return only one final version in %s.
                """.formatted(
                languageName,
                language,
                languageName,
                translateDirective,
                companyName, cnCompany,
                senderName,
                fallback(senderEmail, "N/A"),
                productName, cnProduct,
                valueProposition, cnValue,
                callToAction, cnCta,
                recipients.size(),
                firstRecipient.companyName(),
                firstRecipient.country(),
                hasRealContact ? recipientContact : "N/A",
                hasRealContact,
                recipientEmail,
                fallback(firstRecipient.fitNote(), "Potential customer"), cnFit,
                templateSection,
                languageName
        );
    }

    private String buildTranslationSystemPrompt(String targetLanguageName) {
        return """
                You are a professional translator specializing in business communication.
                Translate the email below into %s.

                Requirements:
                - Preserve the original meaning, tone, and intent.
                - Adapt the translation for business email conventions in the target language.
                - Keep proper nouns (company names, personal names, websites, email addresses) unchanged.
                - Do not add explanations, notes, or markdown formatting.
                - Output format must be exactly:

                SUBJECT: <translated subject>
                BODY:
                <translated body>
                """.formatted(targetLanguageName);
    }

    private String buildTranslationUserPrompt(String subject, String body, String targetLanguageName) {
        return """
                Translate the following email into %s.

                Original subject:
                %s

                Original body:
                %s
                """.formatted(targetLanguageName, subject, body);
    }

    private String buildOptimizationUserPrompt(
            String subject,
            String body,
            String companyName,
            String productName,
            String valueProposition,
            String callToAction,
            String language,
            WorkflowModels.CustomerLead recipient,
            String optimizationLogic,
            String senderName,
            String senderEmail,
            WorkflowModels.EmailTemplateContext template
    ) {
        String languageName = resolveLanguageName(language);
        boolean nonChinese = isNonChineseTarget(language);
        String recipientContact = cleanRecipientContactName(recipient.contactName());
        boolean hasRealContact = !recipientContact.isBlank();
        String translateDirective = nonChinese
                ? "\nMANDATORY TRANSLATION DIRECTIVE: The fields marked with [TRANSLATE TO %s] below contain Chinese text. You MUST translate every Chinese character into %s when composing the email. Do NOT keep any Chinese characters in the final subject or body.\n".formatted(languageName, languageName)
                : "";
        String cnCompany = nonChinese && containsChinese(companyName) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnProduct = nonChinese && containsChinese(productName) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnValue = nonChinese && containsChinese(valueProposition) ? " [TRANSLATE TO " + languageName + "]" : "";
        String cnCta = nonChinese && containsChinese(callToAction) ? " [TRANSLATE TO " + languageName + "]" : "";
        String extraRules = optimizationLogic == null || optimizationLogic.isBlank()
                ? ""
                : "\nAdditional optimization rules:\n" + optimizationLogic.trim() + "\n";
        String templateSection = buildTemplatePromptSection(template, languageName, nonChinese);
        return """
                Target output language: %s (%s)
                Final email rule: the optimized subject and body must be fully written in %s only.%s
                                
                Sender company: %s%s
                Sender name: %s
                Sender email: %s
                Product / solution: %s%s
                Value proposition: %s%s
                CTA: %s%s
                Recipient company: %s
                Recipient country: %s
                Recipient contact: %s
                Has verified personal contact name: %s
                                
                Current subject:
                %s
                                
                Current body:
                %s
                %s
                %s
                                
                Please optimize the subject and body.
                If the current greeting uses website navigation text, button text, or page labels as a person name, replace it with a natural generic greeting.
                Do not preserve fake names such as contact-page labels.
                Return only one final version in %s.
                """.formatted(
                languageName,
                language,
                languageName,
                translateDirective,
                companyName, cnCompany,
                senderName,
                fallback(senderEmail, "N/A"),
                productName, cnProduct,
                valueProposition, cnValue,
                callToAction, cnCta,
                recipient.companyName(),
                recipient.country(),
                hasRealContact ? recipientContact : "N/A",
                hasRealContact,
                fallback(subject, ""),
                fallback(body, ""),
                extraRules,
                templateSection,
                languageName
        );
    }

    private String buildTemplatePromptSection(
            WorkflowModels.EmailTemplateContext template,
            String languageName,
            boolean nonChinese
    ) {
        if (template == null) {
            return "";
        }

        String name = fallback(template.name(), "Selected template");
        String scenario = fallback(template.scenario(), "");
        String subject = fallback(template.subject(), "");
        String body = fallback(template.body(), "");
        String instruction = fallback(template.instruction(), "");
        if (subject.isBlank() && body.isBlank() && instruction.isBlank()) {
            return "";
        }

        String translateDirective = nonChinese && containsChinese(subject + body + instruction)
                ? "\nTemplate translation rule: The selected template contains Chinese text. Use its structure and intent, but translate all Chinese text into " + languageName + "."
                : "";

        return """

                Selected email template:
                Template name: %s
                Scenario: %s
                Template subject:
                %s

                Template body:
                %s

                Template usage notes:
                %s%s
                Template rule: Use this template as loose structure and messaging guidance, not as a fill-in-the-blank form. Replace placeholders naturally with the sender and recipient context. Do not output unresolved placeholders. Improve the wording when the context is thin, and avoid generic empty claims.
                """.formatted(name, scenario, subject, body, instruction, translateDirective);
    }

    private String cleanRecipientContactName(String contactName) {
        String normalized = fallback(contactName, "")
                .replaceAll("[\\p{Cntrl}\\uFFFD]+", " ")
                .replaceAll("[\\p{Punct}&&[^.]]+", " ")
                .replaceAll("\\s+", " ")
                .trim();
        if (normalized.isBlank()) {
            return "";
        }

        String lower = normalized.toLowerCase();
        if (JUNK_CONTACT_TOKENS.stream().anyMatch(token -> lower.equals(token) || lower.contains(token))) {
            return "";
        }
        if (normalized.length() > 32 || normalized.matches(".*\\d{3,}.*") || normalized.contains("@")) {
            return "";
        }

        boolean englishPersonName = normalized.matches("(?i)(mr\\.?|ms\\.?|mrs\\.?|dr\\.?)?\\s*[A-Z][a-z]+(?:\\s+[A-Z][a-z]+){0,2}");
        boolean likelyChinesePersonName = normalized.matches("[\\u4e00-\\u9fff]{2,4}") && !normalized.endsWith("公司");
        return englishPersonName || likelyChinesePersonName ? normalized : "";
    }

    private String cleanGeneratedBody(String body) {
        String cleaned = fallback(body, "");
        if (cleaned.isBlank()) {
            return cleaned;
        }

        cleaned = cleaned.replaceFirst(
                "^[\\s\\p{Punct}a-zA-Z]{0,8}(?:联系我们|联系方式|关于我们|首页|Contact\\s*Us|Contacts|About\\s*Us|Home|Business\\s*Contact)\\s*(您好|你好|您好，|你好，|Hi|Hello|Dear)",
                "$1"
        );
        cleaned = cleaned.replaceFirst("^(您好|你好)\\s+", "$1，");
        return cleaned.trim();
    }

    private String cleanGeneratedText(
            String text,
            String companyName,
            String productName,
            WorkflowModels.CustomerLead recipient,
            String senderName
    ) {
        String cleaned = fallback(text, "");
        if (cleaned.isBlank()) {
            return cleaned;
        }

        String contactName = cleanRecipientContactName(recipient.contactName());
        cleaned = cleaned
                .replace("{{senderName}}", fallback(senderName, ""))
                .replace("{{senderCompany}}", fallback(companyName, ""))
                .replace("{{recipientCompany}}", fallback(recipient.companyName(), ""))
                .replace("{{productName}}", fallback(productName, ""))
                .replace("{{contactName}}", contactName)
                .replace("{{valueProposition}}", "");
        return cleaned.replaceAll("\\{\\{[^}]+}}", "").trim();
    }

    private ParsedDraft parseDraft(String raw) {
        String subject = "";
        String body = raw == null ? "" : raw.trim();

        if (raw == null || raw.isBlank()) {
            return new ParsedDraft(subject, body);
        }

        String[] lines = raw.split("\\R");
        StringBuilder bodyBuilder = new StringBuilder();
        boolean bodyStarted = false;

        for (String line : lines) {
            String trimmed = line.trim();
            if (!bodyStarted && trimmed.regionMatches(true, 0, "SUBJECT:", 0, 8)) {
                subject = trimmed.substring(8).trim();
                continue;
            }
            if (trimmed.equalsIgnoreCase("BODY:")) {
                bodyStarted = true;
                continue;
            }

            if (bodyBuilder.length() > 0) {
                bodyBuilder.append(System.lineSeparator());
            }
            bodyBuilder.append(line);
        }

        if (bodyBuilder.length() > 0) {
            body = bodyBuilder.toString().trim();
        }

        return new ParsedDraft(subject, body);
    }

    private List<String> buildFollowUpTips(WorkflowModels.CustomerLead recipient, int recipientCount) {
        List<String> tips = new ArrayList<>();
        tips.add("24 小时内如果没有回复，可发送一次简短跟进。");
        tips.add("对 " + fallback(recipient.companyName(), "目标客户") + " 这类高匹配客户，建议补充案例或报价信息。");
        if (recipientCount > 1) {
            tips.add("当前草稿适用于 " + recipientCount + " 个已选客户，发送前建议再检查变量是否自然。");
        } else {
            tips.add("当前草稿更适合单客户精细化发送，建议再补一条个性化开场。");
        }
        return tips;
    }

    private String buildFallbackSubject(String companyName, String productName, String recipientCompany) {
        return recipientCompany + " x " + companyName + " | " + productName;
    }

    private String resolveLanguageName(String language) {
        if (language == null || language.isBlank()) {
            return "Simplified Chinese";
        }
        return switch (language.trim()) {
            case "zh", "zh-CN", "zh-Hans" -> "Simplified Chinese";
            case "en", "en-US", "en-GB" -> "English";
            case "de", "de-DE" -> "German";
            case "fr", "fr-FR" -> "French";
            case "es", "es-ES" -> "Spanish";
            case "ru", "ru-RU" -> "Russian";
            case "ar", "ar-SA", "ar-AE" -> "Arabic";
            case "pt", "pt-BR", "pt-PT" -> "Portuguese";
            default -> language.trim();
        };
    }

    private boolean isNonChineseTarget(String language) {
        if (language == null || language.isBlank()) {
            return false;
        }
        String trimmed = language.trim();
        return !(trimmed.equals("zh") || trimmed.equals("zh-CN") || trimmed.equals("zh-Hans"));
    }

    private boolean containsChinese(String text) {
        if (text == null || text.isBlank()) {
            return false;
        }
        return text.codePoints().anyMatch(cp -> cp >= '\u4e00' && cp <= '\u9fff');
    }

    private List<WorkflowModels.CustomerLead> safeRecipients(List<WorkflowModels.CustomerLead> recipients) {
        return recipients == null ? List.of() : recipients;
    }

    private String fallback(String value, String fallbackValue) {
        return value == null || value.isBlank() ? fallbackValue : value.trim();
    }

    private record ParsedDraft(String subject, String body) {
    }
}
